// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhdk9iHuuecTlu6iawYLaRxwjL7Ll0gmk',
    appId: '1:701589250171:web:ed0a2e8d23c6ec27afc2de',
    messagingSenderId: '701589250171',
    projectId: 'car-app-project-35e7d',
    authDomain: 'car-app-project-35e7d.firebaseapp.com',
    storageBucket: 'car-app-project-35e7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2AoDwOiBzI657a5IDI7hvc7QFP_xdbVU',
    appId: '1:701589250171:android:744141d3e23ba6bcafc2de',
    messagingSenderId: '701589250171',
    projectId: 'car-app-project-35e7d',
    storageBucket: 'car-app-project-35e7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTt9VmldxoOBXyEePcUHVUQBDoiOx-hxs',
    appId: '1:701589250171:ios:003280f8010fb25cafc2de',
    messagingSenderId: '701589250171',
    projectId: 'car-app-project-35e7d',
    storageBucket: 'car-app-project-35e7d.appspot.com',
    iosClientId: '701589250171-lcaqtdm67ckta0vsm3mu8g797p0ht90a.apps.googleusercontent.com',
    iosBundleId: 'com.example.carRentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTt9VmldxoOBXyEePcUHVUQBDoiOx-hxs',
    appId: '1:701589250171:ios:003280f8010fb25cafc2de',
    messagingSenderId: '701589250171',
    projectId: 'car-app-project-35e7d',
    storageBucket: 'car-app-project-35e7d.appspot.com',
    iosClientId: '701589250171-lcaqtdm67ckta0vsm3mu8g797p0ht90a.apps.googleusercontent.com',
    iosBundleId: 'com.example.carRentApp',
  );
}
